/**
 * Generates `work-item-fields.ts`: a per-project snapshot of known work-item
 * field names, sourced from `GET /api/projects/{projectId}/work-item-field-options`.
 *
 * `workItem.field(name)` (see `define-default-pipeline-assignment.ts`) is
 * inherently untyped — work-item `fields` keys are platform- and
 * project-dependent (Jira custom field labels, GitHub-specific keys, etc.),
 * so there is no static schema to type them against. This file gives pipeline
 * authors an opt-in escape hatch: pass the generated `WorkItemFieldName`
 * union as `field`'s type parameter (`workItem.field<WorkItemFieldName>("issueType")`)
 * to get compile-time validation and editor autocomplete on field names
 * already seen for this project, while `workItem.field("issueType")` (no
 * type argument) keeps working exactly as before.
 *
 * The generated union is a best-effort snapshot as of the last
 * `boboddy pipelines pull`, not an authoritative schema — new custom fields
 * can appear on the platform side at any time, so this file is regenerated
 * (never hand-edited) on every pull.
 */

export type WorkItemFieldOption = {
  key: string;
  values: string[];
  truncated: boolean;
};

const GENERATED_HEADER =
  "// GENERATED by `boboddy pipelines pull` — do not edit; overwritten on each pull.";

/**
 * Up to this many observed sample values are rendered as a trailing comment
 * on each union member — enough to jog a pipeline author's memory of what a
 * field holds (e.g. is `status` an enum of a few values, or free text?)
 * without ballooning the file for high-cardinality fields.
 */
const MAX_PREVIEW_VALUES = 5;

function renderValuePreview(option: WorkItemFieldOption): string {
  if (option.values.length === 0) return "";
  const preview = option.values
    .slice(0, MAX_PREVIEW_VALUES)
    .map((v) => JSON.stringify(v))
    .join(", ");
  const hasMore = option.truncated || option.values.length > MAX_PREVIEW_VALUES;
  return ` // values: ${preview}${hasMore ? ", …" : ""}`;
}

/**
 * Generate the content of `work-item-fields.ts` from the server's field
 * options response.
 *
 * When `fieldOptions` is empty, emits `export type WorkItemFieldName = never;`
 * rather than omitting the file — this keeps the file's presence/absence
 * from depending on project state, so an import of it never needs to become
 * conditional, and a pipeline referencing `WorkItemFieldName` on a
 * zero-field project gets a clear "never has no members" error instead of a
 * missing-module error.
 */
export function generateWorkItemFieldsFileContent(
  fieldOptions: WorkItemFieldOption[],
): string {
  // Deduplicate by key (last write wins) and sort for stable diffs.
  const byKey = new Map<string, WorkItemFieldOption>();
  for (const option of fieldOptions) {
    byKey.set(option.key, option);
  }
  const sortedKeys = [...byKey.keys()].sort();

  const lines: string[] = [
    GENERATED_HEADER,
    "// Snapshot of work-item field names observed for this project as of the",
    "// last pull. Best-effort, not authoritative — new custom fields can appear",
    "// on the platform side at any time.",
    "//",
    "// Usage: workItem.field<WorkItemFieldName>(\"issueType\").eq(\"bug\")",
    "",
  ];

  if (sortedKeys.length === 0) {
    lines.push("export type WorkItemFieldName = never;");
    return lines.join("\n") + "\n";
  }

  lines.push("export type WorkItemFieldName =");
  sortedKeys.forEach((key, index) => {
    const option = byKey.get(key);
    const isLast = index === sortedKeys.length - 1;
    const preview = option ? renderValuePreview(option) : "";
    lines.push(`  | ${JSON.stringify(key)}${isLast ? ";" : ""}${preview}`);
  });

  return lines.join("\n") + "\n";
}
