import { mkdtemp, readFile, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { pullPipelineDefinitions } from "../../../../src/pipelines/pipeline-definitions/application/pull-pipeline-definitions";

/**
 * Mocks the four GET requests `pullPipelineDefinitions` issues via
 * `globalThis.fetch` (the underlying transport for every generated SDK
 * client), keyed by URL substring — mirroring the mocking style used by
 * `remote-artifact-store.test.ts`.
 */
function mockFetch(responses: {
  steps?: unknown[];
  pipelines?: unknown[];
  project?: Record<string, unknown>;
  fieldOptions?: unknown[];
}): { calls: string[] } {
  const calls: string[] = [];
  // eslint-disable-next-line local/no-unknown-parameter-type -- test helper serializes arbitrary JSON fixtures
  const json = (body: unknown) =>
    Promise.resolve(
      new Response(JSON.stringify(body), {
        status: 200,
        headers: { "content-type": "application/json" },
      }),
    );

  globalThis.fetch = ((input: Request | string) => {
    const url = typeof input === "string" ? input : input.url;
    calls.push(url);
    if (url.includes("/work-item-field-options")) {
      return json(responses.fieldOptions ?? []);
    }
    if (url.includes("/step-definitions")) {
      return json(responses.steps ?? []);
    }
    if (url.includes("/pipeline-definitions")) {
      return json(responses.pipelines ?? []);
    }
    // GET /api/projects/{projectId}
    return json(responses.project ?? {});
  }) as unknown as typeof fetch;

  return { calls };
}

const noopLogger = { info: () => undefined, warn: () => undefined };

describe("pullPipelineDefinitions / work-item-fields.ts", () => {
  const previousFetch = globalThis.fetch;
  let dir: string;

  beforeEach(async () => {
    dir = await mkdtemp(path.join(os.tmpdir(), "pull-pipeline-definitions-"));
  });

  afterEach(async () => {
    globalThis.fetch = previousFetch;
    await rm(dir, { recursive: true, force: true }).catch(() => undefined);
  });

  test("fetches /work-item-field-options and writes work-item-fields.ts", async () => {
    const { calls } = mockFetch({
      steps: [
        {
          id: "step-1",
          projectId: "project-1",
          key: "triage",
          name: "Triage",
          description: null,
          prompt: "Triage it",
          version: 1,
          kind: "user_defined",
          executionMode: "no_workspace",
          inputSchemaJson: null,
          resultSchemaJson: { type: "object", properties: {} },
          opencodeMcpJson: null,
          opencodePluginJson: null,
          healthChecksJson: null,
          signalExtractorDefinitions: [],
        },
      ],
      pipelines: [],
      project: { id: "project-1", defaultPipelineAssignment: null },
      fieldOptions: [
        { key: "issueType", values: ["bug", "task"], truncated: false },
        { key: "status", values: ["open", "resolved"], truncated: false },
      ],
    });

    const result = await pullPipelineDefinitions({
      projectId: "project-1",
      baseUrl: "https://api.test",
      headers: { Authorization: "Bearer token" },
      logger: noopLogger,
      dir,
      sdkVersion: "0.0.0",
    });

    expect(calls.some((url) => url.includes("/work-item-field-options"))).toBe(
      true,
    );
    expect(result.workItemFieldsFile).toBe(true);

    const filePath = path.join(dir, "work-item-fields.ts");
    expect(existsSync(filePath)).toBe(true);
    const content = await readFile(filePath, "utf-8");
    expect(content).toContain(
      "// GENERATED by `boboddy pipelines pull` — do not edit; overwritten on each pull.",
    );
    expect(content).toContain('"issueType"');
    expect(content).toContain('"status"');
  });

  test("writes `never` when the project has no observed fields yet", async () => {
    // At least one step must exist, otherwise `pullPipelineDefinitions`
    // early-returns before reaching the field-options write (see "No
    // pipeline or step definitions found" in the implementation) — that
    // early-return is orthogonal to field-options and covered separately by
    // `result.workItemFieldsFile` being `false` in that case.
    mockFetch({
      steps: [
        {
          id: "step-1",
          projectId: "project-1",
          key: "triage",
          name: "Triage",
          description: null,
          prompt: "Triage it",
          version: 1,
          kind: "user_defined",
          executionMode: "no_workspace",
          inputSchemaJson: null,
          resultSchemaJson: { type: "object", properties: {} },
          opencodeMcpJson: null,
          opencodePluginJson: null,
          healthChecksJson: null,
          signalExtractorDefinitions: [],
        },
      ],
      pipelines: [],
      project: { id: "project-1", defaultPipelineAssignment: null },
      fieldOptions: [],
    });

    const result = await pullPipelineDefinitions({
      projectId: "project-1",
      baseUrl: "https://api.test",
      headers: { Authorization: "Bearer token" },
      logger: noopLogger,
      dir,
      sdkVersion: "0.0.0",
    });

    expect(result.workItemFieldsFile).toBe(true);
    const content = await readFile(
      path.join(dir, "work-item-fields.ts"),
      "utf-8",
    );
    expect(content).toContain("export type WorkItemFieldName = never;");
  });

  test("does not fetch or write work-item-fields.ts when there are no steps or pipelines at all", async () => {
    const { calls } = mockFetch({
      steps: [],
      pipelines: [],
      project: { id: "project-1", defaultPipelineAssignment: null },
      fieldOptions: [{ key: "issueType", values: ["bug"], truncated: false }],
    });

    const result = await pullPipelineDefinitions({
      projectId: "project-1",
      baseUrl: "https://api.test",
      headers: { Authorization: "Bearer token" },
      logger: noopLogger,
      dir,
      sdkVersion: "0.0.0",
    });

    expect(result.workItemFieldsFile).toBe(false);
    expect(existsSync(path.join(dir, "work-item-fields.ts"))).toBe(false);
    // The implementation still issues all four requests in one `Promise.all`
    // before checking the "nothing to pull" condition.
    expect(calls.some((url) => url.includes("/work-item-field-options"))).toBe(
      true,
    );
  });
});
