import { describe, expect, test } from "bun:test";
import {
  generateWorkItemFieldsFileContent,
  type WorkItemFieldOption,
} from "../../../../src/pipelines/pipeline-definitions/infra/work-item-fields-file-generator";

describe("generateWorkItemFieldsFileContent", () => {
  test("emits a sorted WorkItemFieldName union with a generated-file header", () => {
    const options: WorkItemFieldOption[] = [
      { key: "status", values: ["open", "resolved"], truncated: false },
      { key: "issueType", values: ["bug", "task"], truncated: false },
      {
        key: "What are the Company Name(s):",
        values: ["Acme"],
        truncated: false,
      },
    ];

    const output = generateWorkItemFieldsFileContent(options);

    expect(output).toContain(
      "// GENERATED by `boboddy pipelines pull` — do not edit; overwritten on each pull.",
    );
    expect(output).toContain("export type WorkItemFieldName =");

    // Sorted for stable diffs: "What are the Company Name(s):" < "issueType" < "status"
    // by plain string comparison (capital "W" sorts before lowercase letters).
    const unionLines = output
      .split("\n")
      .filter((line) => line.trimStart().startsWith("|"));
    expect(unionLines[0]).toContain('"What are the Company Name(s):"');
    expect(unionLines[1]).toContain('"issueType"');
    expect(unionLines[2]).toContain('"status"');

    // Only the last member terminates the type with a semicolon.
    expect(unionLines[0]).not.toContain(";");
    expect(unionLines[1]).not.toContain(";");
    expect(unionLines[unionLines.length - 1]).toContain('";');
  });

  test("renders a truncated sample-value preview comment per field", () => {
    const output = generateWorkItemFieldsFileContent([
      { key: "issueType", values: ["bug", "task"], truncated: false },
      {
        key: "reporter",
        values: ["alice", "bob", "carol", "dave", "erin", "frank"],
        truncated: true,
      },
    ]);

    expect(output).toContain('"issueType" // values: "bug", "task"');
    expect(output).toMatch(/"reporter";.*\/\/ values: .*, …/);
  });

  test("deduplicates repeated keys, keeping the last occurrence", () => {
    const output = generateWorkItemFieldsFileContent([
      { key: "status", values: ["open"], truncated: false },
      { key: "status", values: ["resolved", "closed"], truncated: true },
    ]);

    const statusLines = output
      .split("\n")
      .filter((line) => line.includes('"status"'));
    expect(statusLines).toHaveLength(1);
    expect(statusLines[0]).toContain('"resolved"');
  });

  test("emits `never` (not an empty union) when there are zero fields", () => {
    const output = generateWorkItemFieldsFileContent([]);

    expect(output).toContain("export type WorkItemFieldName = never;");
    expect(output).toContain(
      "// GENERATED by `boboddy pipelines pull` — do not edit; overwritten on each pull.",
    );
  });
});
