import {
  CONTAINER_RUNTIME_ROOT,
  PAYLOAD_BIN_SUBDIR,
} from "../domain/opencode-runtime-payload";

/**
 * Builds the `launch.sh` wrapper shipped inside the OpenCode runtime payload and
 * invoked by ABSOLUTE PATH inside the devcontainer.
 *
 * The wrapper is the portability seam for the "Runtime payload portability"
 * risk: a single payload must run both inside arbitrary Linux base images
 * (glibc vs musl, arm64 vs x64) AND directly on a macOS host (the
 * `no_workspace` path). At launch it:
 *
 *   1. Resolves its own directory from `$0` (so it works regardless of the
 *      mounted version path — the version dir name is embedded by the mount).
 *   2. Detects the OS via `uname -s` (Darwin -> macOS host; else Linux).
 *   3. Detects the CPU arch via `uname -m` (aarch64 -> arm64, x86_64 -> x64).
 *   4. On Linux, detects libc: if `/etc/alpine-release` exists OR `ldd --version`
 *      mentions musl, selects the `-musl` binary; otherwise the glibc binary.
 *      On macOS, selects the `darwin-<arch>` binary (no libc concept).
 *   5. Execs the selected standalone (embedded-Bun) `opencode` binary with all
 *      forwarded args (e.g. `serve --hostname 127.0.0.1 --port <p>`).
 *
 * It deliberately uses only POSIX `sh` builtins and `uname` (always present),
 * never bash-isms, so it runs on the slimmest images and on macOS `/bin/sh`.
 */
export function buildOpencodeLaunchWrapper(): string {
  // The wrapper resolves binaries relative to its own location, so the absolute
  // version path does not need to be baked in. CONTAINER_RUNTIME_ROOT is only
  // referenced in a diagnostic to keep the wrapper self-describing.
  return `#!/bin/sh
# Boboddy-managed OpenCode runtime launch wrapper.
# Mounted under ${CONTAINER_RUNTIME_ROOT}/opencode/<version> inside a container,
# or invoked directly on the host for no_workspace runs. Selects the correct
# standalone opencode binary for the current OS + arch (+ libc on Linux), then
# execs it. Generated by the worker — do not edit.
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
BIN_ROOT="$SCRIPT_DIR/${PAYLOAD_BIN_SUBDIR}"

# 1. CPU architecture.
machine=$(uname -m)
case "$machine" in
  aarch64 | arm64) arch="arm64" ;;
  x86_64 | amd64) arch="x64" ;;
  *)
    echo "boboddy: unsupported CPU architecture '$machine' for OpenCode runtime payload" >&2
    exit 97
    ;;
esac

# 2. Operating system. macOS hosts (no_workspace) run the darwin binary; every
# other OS is treated as Linux (the devcontainer / Linux-host case).
os=$(uname -s)
if [ "$os" = "Darwin" ]; then
  candidate="$BIN_ROOT/darwin-\${arch}/opencode"
  if [ ! -x "$candidate" ]; then
    echo "boboddy: no OpenCode binary for darwin-\${arch} in $BIN_ROOT" >&2
    exit 98
  fi
  exec "$candidate" "$@"
fi

# 3. Linux libc flavor. Alpine (musl) ships /etc/alpine-release; else probe ldd.
libc=""
if [ -f /etc/alpine-release ]; then
  libc="-musl"
elif ldd --version 2>&1 | grep -qi musl; then
  libc="-musl"
fi

candidate="$BIN_ROOT/linux-\${arch}\${libc}/opencode"

# Fallback: if a musl variant is missing, try glibc (some musl-userland images
# still ship a glibc-compatible loader); and vice-versa.
if [ ! -x "$candidate" ]; then
  if [ -n "$libc" ]; then
    alt="$BIN_ROOT/linux-\${arch}/opencode"
  else
    alt="$BIN_ROOT/linux-\${arch}-musl/opencode"
  fi
  if [ -x "$alt" ]; then
    candidate="$alt"
  fi
fi

if [ ! -x "$candidate" ]; then
  echo "boboddy: no OpenCode binary for linux-\${arch}\${libc} in $BIN_ROOT" >&2
  exit 98
fi

exec "$candidate" "$@"
`;
}
